import { LuPackage, LuCookie, LuTruck } from "react-icons/lu";

export const menuItems = [
    { label: 'Home', ariaLabel: 'Go to home page', link: '/' },
    { label: 'Menu', ariaLabel: 'View our Menu', link: '/menu' },
    { label: 'Build Your Box', ariaLabel: 'Build your own box', link: '/build-box' },
    { label: 'Snack\'d', ariaLabel: 'Limited Drops', link: '/drops' },
    { label: 'Contact', ariaLabel: 'Get in touch', link: '/contact' },
    // { label: 'Cart', ariaLabel: 'View Your Cart', link: '/cart' },
];

export const buildYourBoxOptions = [
  {
    id: "box-4",
    name: "Build Your Box — 4 Cookie Pack",
    size: 4,
    description:
      "Create your perfect mini box! Pick any 4 freshly baked cookies from our signature menu. Mix, match, and craft your own flavor experience — ideal for gifting, cravings, or trying new flavors.",
    price: "Depending On Cookies Flavour", // in PKR or your currency of choice
    image: "/boxoffour.png"
  },
  {
    id: "box-6",
    name: "Build Your Box — 6 Cookie Pack",
    size: 6,
    description:
      "The ultimate cookie treat. Choose any 6 premium cookies to build your dream box. More cookies, more flavor, more happiness — perfect for sharing or indulging all by yourself.",
    price: "Depending On Cookies Flavour", // in PKR or your currency
    image: "/boxofsix.png"
  }
];

export const steps = [
    {
      id: 1,
      icon: LuPackage,
      title: "Pick Your Box",
      description: "Choose between our Box of 4 or Box of 6 cookies."
    },
    {
      id: 2,
      icon: LuCookie,
      title: "Choose Your Flavours",
      description: "Mix & match your favorites — we bake fresh instantly."
    },
    {
      id: 3,
      icon: LuTruck,
      title: "Fresh Delivery",
      description: "Freshly baked and delivered across Lahore."
    }
  ];

  
export const items = [
  { id: "1", img: "https://picsum.photos/600/400?random=1", url: "https://example.com/item-1", height: 420 },
  { id: "2", img: "https://picsum.photos/600/400?random=2", url: "https://example.com/item-2", height: 310 },
  { id: "3", img: "https://picsum.photos/600/400?random=3", url: "https://example.com/item-3", height: 550 },
  { id: "4", img: "https://picsum.photos/600/400?random=4", url: "https://example.com/item-4", height: 290 },
  { id: "5", img: "https://picsum.photos/600/400?random=5", url: "https://example.com/item-5", height: 480 },
  { id: "6", img: "https://picsum.photos/600/400?random=6", url: "https://example.com/item-6", height: 360 },
  { id: "7", img: "https://picsum.photos/600/400?random=7", url: "https://example.com/item-7", height: 520 },
  { id: "8", img: "https://picsum.photos/600/400?random=8", url: "https://example.com/item-8", height: 400 },
  { id: "9", img: "https://picsum.photos/600/400?random=9", url: "https://example.com/item-9", height: 520 },
  { id: "10", img: "https://picsum.photos/600/400?random=10", url: "https://example.com/item-10", height: 470 },
  { id: "11", img: "https://picsum.photos/600/400?random=11", url: "https://example.com/item-11", height: 270 },
  { id: "12", img: "https://picsum.photos/600/400?random=12", url: "https://example.com/item-12", height: 270 }
];

export const reviews = [
  {
    id: "1",
    stars: "5",
    name: "Ali Khan",
    role: "Food Enthusiast",
    comment: "Absolutely loved the cookies! Fresh and delicious.",
    avatar: "https://i.pravatar.cc/150?img=1"
  },
  {
    id: "2",
    stars: "5",
    name: "Sara Ahmed",
    role: "Baker",
    comment: "The flavors are unique and baked perfectly. Highly recommend!",
    avatar: "https://i.pravatar.cc/150?img=2"
  },
  {
    id: "3",
    stars: "5",
    name: "Hamza Iqbal",
    role: "Customer",
    comment: "Fast delivery and amazing taste. Will order again!",
    avatar: "https://i.pravatar.cc/150?img=3"
  },
  {
    id: "4",
    stars: "4",
    name: "Zara Khan",
    role: "Cookie Lover",
    comment: "My kids loved them! Soft, chewy, and sweet.",
    avatar: "https://i.pravatar.cc/150?img=4"
  },
  {
    id: "5",
    stars: "3",
    name: "Usman Ali",
    role: "Sweet Tooth",
    comment: "Quality is top notch. Definitely the best cookies in Lahore!",
    avatar: "https://i.pravatar.cc/150?img=5"
  },
  {
    id: "6",
    stars: "3",
    name: "Ayesha Malik",
    role: "Food Blogger",
    comment: "Beautifully baked and the packaging is so cute!",
    avatar: "https://i.pravatar.cc/150?img=6"
  }
];

export const cookies = [
  {
    id: 1,
    slug: "ruby-velvet-chunk",
    price: 200,
    title: "Ruby Velvet Chunk",
    category: "limited",
    status: "active",
    hotSeller: true,
    description: "A limited deep-red cookie with cream cheese swirls.",
    releaseDate: "2025-12-05T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten"],
    storage: "Store in an airtight container for up to 3 days.",
    heating: "Warm in microwave for 8–10 seconds for best taste.",
  },
  {
    id: 2,
    slug: "choco-lava-blast",
    price: 200,
    title: "Choco Lava Blast",
    category: "limited",
    status: "inactive",
    hotSeller: false,
    description: "Molten chocolate core for real chocolate addicts.",
    releaseDate: "2025-10-10T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten", "Soy"],
    storage: "Keep refrigerated for up to 5 days.",
    heating: "Microwave for 12 seconds for a molten center.",
  },
  {
    id: 3,
    slug: "double-velvet-chunk",
    price: 200,
    title: "Double Velvet Chunk",
    category: "limited",
    status: "active",
    hotSeller: false,
    description: "A limited deep-red cookie with cream cheese swirls.",
    releaseDate: "2025-11-25T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten"],
    storage: "Store in a cool dry place; lasts 3–4 days.",
    heating: "Warm for 6–8 seconds for a soft center.",
  },
  {
    id: 4,
    slug: "classic-choco-lava",
    price: 200,
    title: "Choco Lava Blast Classic",
    category: "classic",
    status: "active",
    hotSeller: true,
    soldOut: true,
    description: "Molten chocolate core—classic version.",
    releaseDate: "2025-12-10T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten", "Soy"],
    storage: "Best stored in a cool place; consume within 4 days.",
    heating: "Heat for 10 seconds for lava center.",
  },
  {
    id: 5,
    slug: "chocolate-chip",
    price: 200,
    title: "Chocolate Chip",
    category: "classic",
    status: "active",
    hotSeller: true,
    description: "Crispy edges, soft center, packed with chocolate.",
    releaseDate: "2025-01-01T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Eggs", "Gluten"],
    storage: "Store for 3–4 days in airtight container.",
    heating: "Microwave for 5–7 seconds.",
  },
  {
    id: 6,
    slug: "red-velvet",
    price: 200,
    title: "Red Velvet",
    category: "classic",
    status: "inactive",
    hotSeller: false,
    description: "Smooth velvety cookie with cream cheese hints.",
    releaseDate: "2025-01-10T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Eggs", "Gluten"],
    storage: "Keep in cool place for 3 days.",
    heating: "Heat 5–6 seconds.",
  },
  {
    id: 7,
    slug: "oatmeal-raisin",
    price: 200,
    title: "Oatmeal Raisin",
    category: "classic",
    status: "active",
    hotSeller: false,
    description: "Chewy oatmeal cookie loaded with raisins.",
    releaseDate: "2025-01-15T00:00:00",
    durationDays: 999,
    allergens: ["Gluten"],
    storage: "Store for 3 days.",
    heating: "No heating needed.",
  },
  {
    id: 8,
    slug: "peanut-butter",
    price: 200,
    title: "Peanut Butter",
    category: "classic",
    status: "active",
    hotSeller: false,
    description: "Soft peanut butter cookie for PB lovers.",
    releaseDate: "2025-01-20T00:00:00",
    durationDays: 999,
    allergens: ["Peanuts", "Milk", "Eggs"],
    storage: "Store airtight for 5 days.",
    heating: "Microwave 4 seconds.",
  },
  {
    id: 9,
    slug: "double-chocolate",
    price: 200,
    title: "Double Chocolate",
    category: "limited",
    status: "inactive",
    hotSeller: true,
    description: "Dark & milk chocolate blend cookie.",
    releaseDate: "2025-02-15T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten", "Soy"],
    storage: "Store for 3 days.",
    heating: "Heat 8 seconds.",
  },
  {
    id: 10,
    slug: "sugar-cookie",
    price: 200,
    title: "Sugar Cookie",
    category: "limited",
    status: "active",
    hotSeller: false,
    description: "Soft buttery sugar cookie.",
    releaseDate: "2025-03-01T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs"],
    storage: "Store airtight for 3 days.",
    heating: "Heat 4 seconds.",
  },
  {
    id: 11,
    slug: "white-choc-macadamia",
    price: 200,
    title: "White Chocolate Macadamia",
    category: "classic",
    status: "active",
    hotSeller: true,
    description: "Creamy white chocolate with crunchy macadamia.",
    releaseDate: "2025-01-10T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Nuts", "Gluten"],
    storage: "Store for 4 days.",
    heating: "Heat 6 seconds.",
  },
  {
    id: 12,
    slug: "salted-caramel-crunch",
    price: 200,
    title: "Salted Caramel Crunch",
    category: "limited",
    status: "active",
    hotSeller: true,
    description: "Caramel-packed cookie with sea salt flakes.",
    releaseDate: "2025-12-12T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Gluten"],
    storage: "Refrigerate for 4 days.",
    heating: "Heat 7 seconds.",
  },
  {
    id: 13,
    slug: "mint-chocolate",
    price: 200,
    title: "Mint Chocolate",
    category: "classic",
    status: "inactive",
    hotSeller: false,
    description: "Refreshing mint mixed with dark chocolate.",
    releaseDate: "2025-03-15T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Gluten"],
    storage: "Store 3 days.",
    heating: "Heat 5 seconds.",
  },
  {
    id: 14,
    slug: "brownie-blast",
    price: 200,
    title: "Brownie Blast",
    category: "limited",
    status: "active",
    hotSeller: true,
    description: "Brownie-like cookie with gooey center.",
    releaseDate: "2025-11-20T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten"],
    storage: "Store airtight 3 days.",
    heating: "Heat 9 seconds.",
  },
  {
    id: 15,
    slug: "strawberry-dream",
    price: 200,
    title: "Strawberry Dream",
    category: "classic",
    status: "active",
    hotSeller: false,
    description: "Strawberry infused soft cookie.",
    releaseDate: "2025-02-05T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Eggs"],
    storage: "Store 3 days.",
    heating: "Heat 4 seconds.",
  },
  {
    id: 16,
    slug: "nutella-core",
    price: 200,
    title: "Nutella Core",
    category: "limited",
    status: "active",
    hotSeller: true,
    description: "A thick cookie stuffed with Nutella.",
    releaseDate: "2025-12-20T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Hazelnuts", "Gluten"],
    storage: "Store 3 days.",
    heating: "Heat 10 seconds.",
  },
  {
    id: 17,
    slug: "banana-choc-chip",
    price: 200,
    title: "Banana Chocolate Chip",
    category: "classic",
    status: "inactive",
    hotSeller: false,
    description: "Banana flavored cookie with choco chips.",
    releaseDate: "2025-01-25T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Eggs"],
    storage: "Store 2 days.",
    heating: "Heat 3 seconds.",
  },
  {
    id: 18,
    slug: "coffee-crunch",
    price: 200,
    title: "Coffee Crunch",
    category: "classic",
    status: "active",
    hotSeller: true,
    description: "Coffee-infused cookie with a crunchy bite.",
    releaseDate: "2025-02-10T00:00:00",
    durationDays: 999,
    allergens: ["Milk", "Gluten"],
    storage: "Store 4 days.",
    heating: "Heat 5 seconds.",
  },
  {
    id: 19,
    slug: "lotus-biscoff",
    price: 200,
    title: "Lotus Biscoff",
    category: "limited",
    status: "active",
    hotSeller: true,
    description: "Caramelized Biscoff paste inside a soft cookie.",
    releaseDate: "2025-12-30T00:00:00",
    durationDays: 7,
    allergens: ["Soy", "Gluten"],
    storage: "Store 3–4 days.",
    heating: "Heat 7 seconds.",
  },
  {
    id: 20,
    slug: "oreo-stuffed",
    price: 200,
    title: "Oreo Stuffed Cookie",
    category: "limited",
    status: "inactive",
    hotSeller: false,
    description: "A full Oreo stuffed inside a soft cookie.",
    releaseDate: "2025-11-10T00:00:00",
    durationDays: 7,
    allergens: ["Milk", "Eggs", "Gluten", "Soy"],
    storage: "Store 3 days.",
    heating: "Heat 6 seconds.",
  }
].map(cookie => {
  const now = new Date();
  const release = new Date(cookie.releaseDate);
  const end = new Date(release);
  end.setDate(end.getDate() + cookie.durationDays);

  return {
    ...cookie,
    soldOut: now >= end
  };
});

