import type { Metadata } from "next";
import "./globals.css";
import { mainFont } from "@/lib/font/font";
import { DropProvider } from "@/lib/context/contextAPI";
import MetaPixel from "@/components/adminComp/MetaPixel";

export const metadata: Metadata = {
  title: "Chunk'd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body className={`${mainFont.className} antialiased`}>
        <DropProvider>
          <MetaPixel />
          {children}
        </DropProvider>
      </body>
    </html>
  );
}
