import type { Metadata } from "next";
import "./globals.css";
import { mainFont } from "@/lib/font/font";


export const metadata: Metadata = {
  title: "Chunk'd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
